# Generated by Django 4.0 on 2021-12-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.TextField(max_length=200)),
                ('image_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Degree', models.CharField(max_length=15)),
                ('Date_Of_Graduation', models.DateField()),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=15)),
                ('Message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Date_Of_Earn', models.DateField()),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Date_Of_earn', models.DateField()),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoer',
            fields=[
                ('T_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Task', models.CharField(max_length=20)),
                ('Task_category', models.CharField(max_length=20)),
                ('Deadline', models.DateField()),
                ('Description', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('E_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('Amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
